# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: packethost 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "packethost"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jake Bell", "Emiliano Jankowski", "Andrew Hodges"]
  s.date = "2016-01-11"
  s.description = "Ruby client for the Packet API"
  s.email = ["jake@packet.net", "emiliano@packet.net", "andy@packet.net"]
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".rubocop.yml",
    ".travis.yml",
    "CHANGELOG.md",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "lib/packet.rb",
    "lib/packet/client.rb",
    "lib/packet/client/devices.rb",
    "lib/packet/client/facilities.rb",
    "lib/packet/client/operating_systems.rb",
    "lib/packet/client/plans.rb",
    "lib/packet/client/projects.rb",
    "lib/packet/client/ssh_keys.rb",
    "lib/packet/client/users.rb",
    "lib/packet/configuration.rb",
    "lib/packet/device.rb",
    "lib/packet/entity.rb",
    "lib/packet/entity/associations.rb",
    "lib/packet/entity/base.rb",
    "lib/packet/entity/finders.rb",
    "lib/packet/entity/persistence.rb",
    "lib/packet/entity/serialization.rb",
    "lib/packet/entity/timestamps.rb",
    "lib/packet/errors.rb",
    "lib/packet/facility.rb",
    "lib/packet/global_id.rb",
    "lib/packet/operating_system.rb",
    "lib/packet/plan.rb",
    "lib/packet/project.rb",
    "lib/packet/ssh_key.rb",
    "lib/packet/user.rb",
    "lib/packet/version.rb",
    "packethost.gemspec",
    "spec/fixtures/operating_systems.json",
    "spec/fixtures/plans.json",
    "spec/fixtures/project.json",
    "spec/fixtures/projects.json",
    "spec/fixtures/ssh_key.json",
    "spec/fixtures/ssh_keys.json",
    "spec/lib/packet/client_spec.rb",
    "spec/lib/packet/configuration_spec.rb",
    "spec/lib/packet/project_spec.rb",
    "spec/lib/packet_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/fake_packet.rb",
    "spec/support/shared/entity.rb",
    "spec/support/webmock.rb"
  ]
  s.homepage = "http://github.com/packethost/packet-rb"
  s.licenses = ["GPL-2.0"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "Ruby client for the Packet API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<packethost>, [">= 0"])
      s.add_development_dependency(%q<rake>, ["~> 0"])
      s.add_development_dependency(%q<rspec>, ["~> 3"])
      s.add_development_dependency(%q<webmock>, ["~> 1.20"])
      s.add_development_dependency(%q<rdoc>, ["~> 4"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, ["~> 0"])
      s.add_development_dependency(%q<rubocop>, ["~> 0"])
      s.add_development_dependency(%q<sinatra>, ["~> 1.4"])
      s.add_development_dependency(%q<pry>, [">= 0"])
    else
      s.add_dependency(%q<packethost>, [">= 0"])
      s.add_dependency(%q<rake>, ["~> 0"])
      s.add_dependency(%q<rspec>, ["~> 3"])
      s.add_dependency(%q<webmock>, ["~> 1.20"])
      s.add_dependency(%q<rdoc>, ["~> 4"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, ["~> 0"])
      s.add_dependency(%q<rubocop>, ["~> 0"])
      s.add_dependency(%q<sinatra>, ["~> 1.4"])
      s.add_dependency(%q<pry>, [">= 0"])
    end
  else
    s.add_dependency(%q<packethost>, [">= 0"])
    s.add_dependency(%q<rake>, ["~> 0"])
    s.add_dependency(%q<rspec>, ["~> 3"])
    s.add_dependency(%q<webmock>, ["~> 1.20"])
    s.add_dependency(%q<rdoc>, ["~> 4"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, ["~> 0"])
    s.add_dependency(%q<rubocop>, ["~> 0"])
    s.add_dependency(%q<sinatra>, ["~> 1.4"])
    s.add_dependency(%q<pry>, [">= 0"])
  end
end

